// <auto-generated />
namespace MBHelper.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class LastUpdatedPrice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LastUpdatedPrice));
        
        string IMigrationMetadata.Id
        {
            get { return "201303061453392_LastUpdatedPrice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
