// <auto-generated />
namespace MBHelper.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class prices : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(prices));
        
        string IMigrationMetadata.Id
        {
            get { return "201303291845453_prices"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
